name: CI/CD

on:
  push
  pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        CI : false
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Lint the commit
      run: npm run lint

    - name: Build
      run: npm run build